/**
 * Purpose: Provide the root layout for the Sanity Studio route group.
 * Main responsibilities: Apply shared fonts and document metadata.
 * Key collaborators: Uses Next.js metadata and font helpers.
 */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

/**
 * Purpose: Register the Studio sans font for typography.
 * Main responsibilities: Provide a CSS variable for font styling.
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/**
 * Purpose: Register the Studio monospace font for code views.
 * Main responsibilities: Provide a CSS variable for monospace styling.
 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Purpose: Define default metadata for the Sanity Studio layout.
 * Main responsibilities: Set title and description values.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Purpose: Render the HTML shell for the Studio route group.
 * Main responsibilities: Apply font classes and render child routes.
 * Inputs/outputs: Receives React children and returns layout markup.
 */
function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}

export default Layout;
